### ISSUE TITLE
Speed up mmseqs for large database and multiple large query sets by loading target into memory 

### ISSUE THREAD

**Issue by dhwanidesai** [soedinglab/MMseqs2#214] opened 2019-06-27 13:15 UTC
## Expected Behavior
Hello Dr. Soeding,
I have been trying to use your program MMSEQs2 to match illumina metagenomic reads against the Refseq proteins database. 
This is the workflow I have followed so far
- create mmseqs db for the target (Refseq here) 
 mmseqs createdb RSComplete/*.gz mmseqsRefSeqCompleteDB
- create an index for the target db (in a temp folder "tmp")
mmseqs createindex RefSeqCompleteDB tmp 
- load the target into memory for repeated searching
mmseqs touchdb mmseqsRefSeqCompleteDB

And then for a set of query files: 
- create mmseqs db for the query file
mmseqs createdb $file $outpath/$querydb
- search against the target db loaded in memory
mmseqs search $outpath/$querydb $db $outpath/$result_db tmp --db-load-mode 3 --threads 2 --max-seqs 25 -s 1 -a -e 1e-5

Is this the correct way of processing multiple searches using mmseqs? Is there any way to speed up searches for large query sets and large database files?

Any information would be greatly appreciated.
Thanking you,

regards,
Dhwani Desai
## Current Behavior
It does not seem to make a difference to the runtime when I try it with or without the --db-load-mode option. Is there a way to speed up these kinds of repeated searches?
## Steps to Reproduce (for bugs)
Please make sure to execute the reproduction steps with newly recreated and empty tmp folders.

## MMseqs Output (for bugs)
Please make sure to also post the complete output of MMseqs. You can use gist.github.com for large output.

## Context
Providing context helps us come up with a solution and improve our documentation for the future.

## Your Environment
Include as many relevant details about the environment you experienced the bug in.
* Git commit used (The string after "MMseqs Version:" when you execute MMseqs without any parameters):
MMseqs2 Version: 73ce3b88754987122b4fc5e69a721beeecd677d0

* Which MMseqs version was used (Statically-compiled, self-compiled, Homebrew, etc.):
installation (using Git):
git clone https://github.com/soedinglab/MMseqs2.git
cd MMseqs2
mkdir build
cd build
cmake -DCMAKE_BUILD_TYPE=RELEASE -DCMAKE_INSTALL_PREFIX=. ..
make
make install 
This will generate the compiled executable in the bin folder
Copy the executable to $HOME/bin
cp bin/mmseqs ~/bin

* For self-compiled and Homebrew: Compiler and Cmake versions used and their invocation:
* Server specifications (especially CPU support for AVX2/SSE and amount of system memory):
* Operating system and version:

**Comment by martin-steinegger** [comment] 2019-06-27 14:12
@dhwanidesai so you perform millions of read searches against the refseq database at once right? Could you please provide an output log of your run? It would help me to understand whats the bottleneck in your analysis.

**Comment by dhwanidesai** [comment] 2019-06-28 12:42
Hi Martin,

Yes. I have a set of query files, each with around 10-15 million reads and a database which has ~130 million sequences. The index file generated by the createindex step is about ~ 400GB in size. The computer I am running this on has around 1.5 TB of RAM so reading this index into memory should not be an issue.

However, when I run the search with and without the --db-load-mode 3 option (i have also tried --db-load-mode 2), it does not make any difference to the run time. In both cases it takes around 8-9 hours to run through all samples. My question is, am I doing the loading into memory correctly? Are there any other options I should be using to speed this up?


I ran the steps thru a script for automating it, so I do not have the logfiles for the run (I wrote it to /dev/null). I can re-run it to generate the logfiles, but it would take some time.


regards,

Dhwani

________________________________

**Comment by dhwanidesai** [comment] 2019-06-28 13:05
Hi Martin,

Yes. I have a set of query files, each with around 10-15 million reads and a database which has ~130 million sequences. The index file generated by the createindex step is about ~ 400GB in size. The computer I am running this on has around 1.5 TB of RAM so reading this index into memory should not be an issue.

However, when I run the search with and without the --db-load-mode 3 option (i have also tried --db-load-mode 2), it does not make any difference to the run time. In both cases it takes around 8-9 hours to run through all samples. My question is, am I doing the loading into memory correctly? Are there any other options I should be using to speed this up?


I ran the steps thru a script for automating it, so I do not have the logfiles for the run (I wrote it to /dev/null). I can re-run it to generate the logfiles, but it would take some time.


regards,

Dhwani

**Comment by dhwanidesai** [comment] 2019-06-28 18:50
A related question is:
After loading the DB into memory and running the searches, does the DB still stay in memory? How do i free up the memory after the run is done? Do I have to load the DB into memory before comparison of every query file with the DB?

**Comment by martin-steinegger** [comment] 2019-06-30 21:46
It would help if you could provide a log file. So I can see which module is slow. 

The database does not stay necessarily memory. The OS can reuse the memory. The memory just got memory mapped by mmseqs2 (depending on the --db-load-mode).

**Comment by dhwanidesai** [comment] 2019-07-03 13:08
Hi Martin,

Here is a logfile for one of the samples that I ran. I had to remove all the "=" signs printed in it (as indicator of progress) because otherwise it increased the file size to ~13GB.


Please let me know if I am using mmseqs correctly or if there is some other trick to speed it up...


regards,

Dhwani

________________________________

**Comment by martin-steinegger** [comment] 2019-07-03 20:18
This is way too slow. I just ran something in a similar scale (query size 10005733, target size 101055107) in less than 10 minutes total. Could it be that your file system is very slow? What would happen if you set the `tmp` to `/dev/shm`? Why do you just use two threads? What kind of CPUs does the computer have?

**Comment by dhwanidesai** [comment] 2019-07-04 13:34
I am trying to parallelize the pipeline so that each sample runs on a single core with two threads.

The computer I am running this on has 80 cpus and about 1.5TB RAM. So I could use more processors per sample, but I wanted to optimize this for single processor per sample.


How many processors did you run your job on that took 10 minutes?


I can try using /dev/shm instead of tmp and see if it makes any difference. We also have a Solid state drive on this computer. Do you think it would be faster if my database is on this drive?


regards,

Dhwani


________________________________

**Comment by martin-steinegger** [comment] 2019-07-08 19:19
Did using the /dev/shm or the SSD improve the run time? 

I used 32 threads for the 10 minutes run. I did not use /dev/shm for the results. What happens if you use more cores?

**Comment by genomewalker** [comment] 2019-07-08 19:34
Hi Martin
maybe this is related to this issue but we have seen similar behavior when we are running more than one mmseqs2 instance per cluster node in an array job for example. We also tried to run them in `/dev/shm` instead of the local scratch but we observed the same slow searches. I will ask @ChiaraVanni to send some logs.

Thanks
Antonio

**Comment by martin-steinegger** [comment] 2019-07-09 06:24
Thank you Antonio! Do you have any idea what caused this? @salvoc81 reported once a similar multi mmseqs2 instance issues. But this should have been fixed by removing the OMP_PROC_BIND flag. Is it possible that you have set this variable?

**Comment by martin-steinegger** [comment] 2019-07-11 15:55
@milot-mirdita noticed that the interactive progress bar could be a problem, in your case it produced at 13GB output. You can turn of the interactive progress bar by setting the environment variable to TTY=0.

**Closed** 2019-10-07 13:00 UTC

**Comment by dhwanidesai** [comment] 2019-10-07 13:07
Thanks for the suggestion. I'll do that for future runs to avoid the huge logfiles.


Re: my original problem, I want to mention that I am using a Perl script (which parallel::forkmanager) to fork separate jobs for each sample in my list and then run each sample separately. I tried running mmseqs search with "--threads 10" using this same script, but I noticed that the intermediate steps in the command (extractorfs, align etc) all just used one process per sample. I am still trying to figure out if it is because of the parallel script or something to do with mmseqs itself.

If I run the same search command on the terminal with "--threads 10" it goes fast

________________________________

**Comment by milot-mirdita** [comment] 2019-10-07 13:26
I suspect that `forkmanager` does weird things to the CPU affinity of MMseqs2 (either on purpose or by accident). I also wouldn't recommend running multiple MMseqs2 run in parallel since the crucial prefiltering step is quite sensitive to the available RAM bandwidth.

I would recommend to do large searches that include all samples in one database. With the recently implemented set ids this will then also become easy to unravel again:
You can use the `qset,qsetid,tset,tsetid` fields in the `convertalis`' `--format-output` parameter  to resolve from which input file an alignment came from.

**Comment by gezmi** [comment] 2021-08-11 06:30
Hi! I also have this problem with slow searches after loading the DB to memory. I have 135,301,051 sequences in the targetDB (uniref90) and so far only trying to use one search sequence. I am using 40 threads and have more memory than the estimated memory consumption. I am using -s 1 and --db-load-mode 3, after doing touchdb. The search created 17 splits, in 10 mins, the prefiltering step did not even finish with the first split.

Is this the expected behavior? Is it only for the 1st sequence that takes too long? Do you have any suggestion to speed up the search?

The extended prefilter command:
`prefilter targetDB /vol/ek/share/alphafold/databases/uniref90/uniref90.idx /dev/shm//6569854898554735840/pref_0 --sub-mat nucl:nucleotide.out,aa:blosum62.out --seed-sub-mat nucl:nucleotide.out,aa:VTML80.out -k 0 --k-score 2147483647 --alph-size nucl:5,aa:21 --max-seq-len 65535 --max-seqs 300 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 3 --pca 1 --pcb 1.5 --threads 40 --compressed 0 -v 3 -s 1.0`

Thank you!

**Comment by milot-mirdita** [comment] 2021-08-11 17:11
You probably should not place the tmp folder inside `/dev/shm`. The intermediate results will compete with the database index and bring everything to a crawl.

**Comment by gezmi** [comment] 2021-08-11 18:30
> You probably should not place the tmp folder inside `/dev/shm`. The intermediate results will compete with the database index and bring everything to a crawl.

Thank you for the answer! Indeed, I tried several paths for tmp - in the working directory, the` /tmp `path of our cluster which should be fast to read and write, and also the` /dev/shm` which was suggested somewhere in the issues. Can you confirm that this is indeed not the expected speed and we should look for the problem that slows it down?
