### ISSUE TITLE
Invalid database read for database data file

### ISSUE THREAD

**Issue by CHEN-Zhihan** [soedinglab/MMseqs2#64] opened 2018-02-18 12:20 UTC
https://github.com/soedinglab/MMseqs2/blob/8e0f4d5a1652d76f1ac07b32e4a7f005116a61e6/src/commons/DBReader.cpp#L342

Is it possible that id is negative? I just received 
"Invalid database read for database data file" for mmseqs convertalis.

And specifically, mmseqs further complained that 
"getData: local id (4294967295) >= db size (1293676)"

Since the local id is -1, I am wondering if I did anything wrong.

Many thanks.

**Comment by martin-steinegger** [comment] 2018-02-18 13:38
Thanks for reporting this issue. Could you please give us the commands to reproduce the issue?

**Comment by CHEN-Zhihan** [comment] 2018-02-19 14:28
Hi Martin,
Thanks for your reply.
It's just normal procedure of alignment. I am not sure whether it is easily reproducible because the same script worked on another machine.

I used:

`mmseqs createdb infile refDB
mmseqs createdb queryfile queryDB
mmseqs search queryDB refDB resultDB ~/tmp/
mmseqs convertalis queryDB refDB resultDB resultDB.m8`

I am redoing the search on that machine and hopefully I didn't do anything incorrect. Will inform you the result.

**Comment by martin-steinegger** [comment] 2018-02-19 14:45
Thanks for your reply. The command looks fine. Could you add the log of the run? What kind of mmseqs version do you use (static or self compiled)? Would it be possible to provide the infile and queryfile to reproduce the issue?

**Comment by CHEN-Zhihan** [comment] 2018-02-21 15:21
Hi Martin,

I just redo the experiment and the result is the same.
I am using static mmseqs with SSE4 with version 9827e74c1e12875f9201302fc8693565c4a973de

Attached is the running log.

<pre><code>
Program call:
read.query nr.mmseqs resultDB result.m8 

MMseqs Version: 	9827e74c1e12875f9201302fc8693565c4a973de
Alignment Format	0
No preload      	false
Early exit      	false
Database Output 	false
Threads         	24
Verbosity       	3

Query Header file: read.query_h
Target Header file: nr.mmseqs_h
Alignment database: resultDB
Start writing file to result.m8
Invalid database read for database data file=Invalid database read for database data file=read.query_h, database index=read.query_h, database index=read.query_h.index
getData: local id (4294967295) >= db size (1293676)
read.query_h.index
getData: local id (4294967295) >= db size (1293676)
</code></pre>

For the infile and queryfile, I am sorry that I may not be able to provide them. But I have performed the experiment with the same settings and commands successfully on another machine with 64GB. But it failed on a machine with 192GB. Not sure whether that matters.

Thanks.

**Comment by martin-steinegger** [comment] 2018-02-23 04:30
It is indeed important to know what the machines specification is since it works on the 64GB machine but not on the 192GB one. From your description, it sounds like the issue coming from a different OS / CPU. Could you please give me the specifications of the computers?

**Comment by martin-steinegger** [comment] 2018-03-01 15:32
Is this issue solved?

**Comment by CHEN-Zhihan** [comment] 2018-03-07 06:16
Hi Martin,

No the issue is still there. The machine was Ubuntu 16.04.2 with 192 GB RAM and Intel E5-2620 CPU.

I tried to use GDB to debug DBReader.cpp and I found that at

https://github.com/soedinglab/MMseqs2/blob/8e0f4d5a1652d76f1ac07b32e4a7f005116a61e6/src/commons/DBReader.cpp#L398

there is a case where dbKey and id are 0 but index[id].id is 1.

Since I no longer need to converalis, it is OK for me to close this issue.

**Comment by martin-steinegger** [comment] 2018-03-07 06:49
Thank you for debugging it! This helps me a lot.  

We should not close this issue since it is not solved yet. Why don't you need convertalis anymore? 
It is really strange that dbKey is = 0. This should not happen. 

Could you do me a favor and figure out which getId call in convertalignments.cpp creates the problem? Line 61, 171 or 176? Thanks a lot!

**Comment by CHEN-Zhihan** [comment] 2018-03-08 01:04
It comes from 

https://github.com/soedinglab/MMseqs2/blob/8e0f4d5a1652d76f1ac07b32e4a7f005116a61e6/src/util/convertalignments.cpp#L171

i.e, the queryKey is 0.

Then I go to

https://github.com/soedinglab/MMseqs2/blob/8e0f4d5a1652d76f1ac07b32e4a7f005116a61e6/src/commons/DBReader.cpp#L380-L391

for alnDbr using LINEAR_ACCESS, it turns out that index[id].id is 0 for a specific id. Do you have any suggestion?

**Comment by martin-steinegger** [comment] 2018-03-27 05:47
@CHEN-Zhihan I really do not know what could be the problem. The only thing I could think off is the input file. Maybe it got corrupted before and now it produces this strange error. The wrong values that are read from the `.index` file.

**Comment by zkstewart** [comment] 2018-04-01 01:57
Hi,

I am experiencing a similar/the same issue when running convertalis. I've used a previous version a few months ago with no issues, so this seems like it's been introduced since then. When using the latest release (2-23394, I tried both avx and sse) I receive this output.

```
n8942188@lyra03:~/test_mmseqs2> /home/n8942188/various_programs/mmseqs2/bin/mmseqs convertalis mmseqstest_nucl.fasta_QDB mmseqtest_prots.fasta_TDB mmseqtest_SDB mmseqtest_SDB.m8 --threads 1
Program call:
mmseqstest_nucl.fasta_QDB mmseqtest_prots.fasta_TDB mmseqtest_SDB mmseqtest_SDB.m8 --threads 1

MMseqs Version:         2339462c06eab0bee64e4fc0ebebf7707f6e53fd
Alignment Format        0
No preload              false
Early exit              false
Database Output         false
Threads                 1
Verbosity               3

Query Header file: mmseqstest_nucl.fasta_QDB_h
Use index  mmseqstest_nucl.fasta_QDB.sk6
Index version: 5.0.0
Generated by:  2339462c06eab0bee64e4fc0ebebf7707f6e53fd
KmerSize:     6
AlphabetSize: 21
Mask:         1
Type:         1
Spaced:       1
KmerScore:    0
SequenceType: 0
Headers:      1
ScoreMatrix:  blosum62.out
Target Header file: mmseqtest_prots.fasta_TDB_h
Use index  mmseqtest_prots.fasta_TDB.sk6
Index version: 5.0.0
Generated by:  2339462c06eab0bee64e4fc0ebebf7707f6e53fd
KmerSize:     6
AlphabetSize: 21
Mask:         1
Type:         1
Spaced:       1
KmerScore:    0
SequenceType: 0
Headers:      1
ScoreMatrix:  blosum62.out
Alignment database: mmseqtest_SDB
Start writing file to mmseqtest_SDB.m8
Invalid database read for database data file=mmseqstest_nucl.fasta_QDB_h, database index=
```

All the previous steps seem to work correctly (createdb, createindex, search) and have contents inside their files. For example, running head on the _QDB_h and _TDB_h files return the below result (both _h files are identical since my query is the nucleotide version of the prot sequence)

```
evm.model.utg902.1.8.5abb479e
evm.model.utg902.1.9.5abb479e
evm.model.utg902.1.10.5abb479e
evm.model.utg1004.80
evm.model.utg8847.1_evm.model.utg8847.2.3.5abb479e
evm.model.utg8847.1_evm.model.utg8847.2
evm.model.utg8847.1_evm.model.utg8847.2.5.5abb479e
evm.model.utg1937.4
evm.model.utg12562.19
```

Head of the mmseqstest_nucl.fasta_QDB_h_index file == 

```
1       0       32
2       32      32
3       64      33
4       97      23
5       120     53
6       173     42
7       215     53
8       268     22
9       290     24
```

The _SDB file has this as its head

```
2       585     0.986   1.536E-193      1248    2085    1044    0       279     281
1       514     0.877   2.516E-168      1248    2085    1044    0       280     282
3       497     0.852   1.632E-162      1248    2085    1044    0       280     282
7       365     1.000   2.704E-120      1075    1579    507     0       168     170
6       316     0.883   2.496E-103      1075    1579    507     0       170     172
5       306     0.857   1.240E-99       1075    1579    507     0       170     172
3       591     0.993   2.689E-197      1081    1921    843     0       280     282
1       520     0.886   7.407E-172      1081    1921    843     0       280     282
2       493     0.845   2.708E-162      1081    1921    843     0       279     281
1       591     0.993   2.689E-197      1081    1921    843     0       280     282
```

The reason I was performing this test was to see how nucleotide -> protein searches worked and to see if the little wrapper script I made to automate MMS2 searches needed any modifications. I figured I'd try using the protein DB as both query and target which resulted in search and convertalis working perfectly. Thus, I think the issue me and @CHEN-Zhihan are having is occurring when performing a nucleotide -> protein search (based off his query file being named "read.fasta" I expect that it is a nucleotide sequence) and seems to be limited to the convertalis step since search looks fine to me.

Does this sound right to you?

Zac.

**Comment by maedat** [comment] 2018-05-15 07:57
Hi. 

I am also experiencing a similar issue when running convertalis after the nucleotide -> protein searching, with MMseqs2 Version: 2339462c06eab0bee64e4fc0ebebf7707f6e53fd.

Do you have any solutions?

Taro

**Comment by martin-steinegger** [comment] 2018-05-18 05:04
Thanks all for helping. I found the bug and fixed it. 
Please update the repository. I will make a new release soon.

**Comment by maedat** [comment] 2018-05-18 05:17
Awesome! 
Thank you for your effort and rapid reaction. 
Taro

**Closed** 2018-06-06 15:05 UTC

**Comment by orenavram** [comment] 2019-03-10 13:24
Having the same issue when using convertalis..
>> convertalis $outdir/b6_aa $outdir/b1_aa $outdir/b6vsb1_alnOffsetedDB $outdir/b6vsb1_alnOffsetedDB.m8
...
Invalid database read for database data file=out10/b6_aa_h, database index=out10/b6_aa_h.index
getData: local id (4294967295) >= db size (4455)

Did you solve it?

**Comment by Luofan-KK** [comment] 2022-10-28 13:04
Having the same issue when using expandaln (following colab fold protocal)

**Comment by ToHanwei** [comment] 2023-03-31 03:01
Having the same issue when using "mmseqs align".

When i use the command:
```mpirun --pernode --bind-to none mmseqs align CORDclust/ClusterDB/CLUSTERDB_step1_redundancy CORDclust/ClusterDB/CLUSTERDB_step1_redundancy CORDclust/PrefilterDB/PREFILTER_step1_prefdb CORDclust/PrefilterDB/PREFILTER_step1_aln -c 0.9 --alignment-mode 2 --min-seq-id 0.9 --comp-bias-corr 0 -e 0.001 --max-seq-len 32768 --max-rejected 2147483647```

I encounter a error:
Invalid database read for database data file=CORDclust/ClusterDB/CLUSTERDB_step1_redundancy, database index=CORDclust/ClusterDB/CLUSTERDB_step1_redundancy.index
getData: local id (4294967295) >= db size (877192)

The odd thing is that when I use a small data set as input, this error does not occur when I run the same script.

**Comment by bchodkowski-vir** [comment] 2023-04-13 16:42
I also get the "Invalid database read for database data file" error from `expandaln` when called by `colabfold_search`

```
Invalid database read for database data file=/home/username/project/my_local_DB/target_DB.idx, database index=/home/username/project/my_local_DB/target_DB.idx.index
getData: local id (4294967295) >= db size (22)
```

I created `target_DB` from `target.fasta` which has 142 records in it:

```
pwd
  # /home/username/project/my_local_DB

mmseqs createdb target.fasta target_DB
mmseqs createindex target_DB tmp_createindex --threads 96

indexdb target_DB target_DB --seed-sub-mat 'aa:VTML80.out,nucl:nucleotide.out' -k 0 --alph-size aa:21,nucl:5 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-seq-len 65535 --max-seqs 300 --mask 1 --mask-prob 0.9 --mask-lower-case 0 --spaced-kmer-mode 1 -s 7.5 --k-score seq:0,prof:0 --check-compatible 0 --search-type 0 --split 0 --split-memory-limit 0 -v 3 --threads 96
```

Then I ran `colabfold_search`.  Output is below.

```
CUDA_VISIBLE_DEVICES='0' colabfold_search
    -s '8'
    --db1 'target_DB'
    --use-templates '0'
    --db2 ''
    --use-env '0'
    --db3 ''
    --filter '1'
    --mmseqs 'mmseqs'
    --expand-eval '1.7e+308'
    --align-eval '10'
    --diff '3000'
    --qsc '-20.0'
    --max-accept '1000000'
    --db-load-mode '2'
    --threads '96'
        query.fasta
        /home/username/project/my_local_DB
        result_query_20230412_142303

createdb result_query_20230412_142303/query.fas result_query_20230412_142303/qdb --shuffle 0

search result_query_20230412_142303/qdb /home/username/project/my_local_DB/target_DB result_query_20230412_142303/res result_query_20230412_142303/tmp --threads 96 --num-iterations 3 --db-load-mode 2 -a -s 8 -e 0.1 --max-seqs 10000

prefilter result_query_20230412_142303/qdb /home/username/project/my_local_DB/target_DB.idx result_query_20230412_142303/tmp/18292001434761310910/pref_0 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --seed-sub-mat 'aa:VTML80.out,nucl:nucleotide.out' -s 8 -k 0 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seq-len 65535 --max-seqs 10000 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --comp-bias-corr-scale 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-prob 0.9 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 2 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --threads 96 --compressed 0 -v 3

align result_query_20230412_142303/qdb /home/username/project/my_local_DB/target_DB.idx result_query_20230412_142303/tmp/18292001434761310910/pref_0 result_query_20230412_142303/tmp/18292001434761310910/aln_0 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 1 --alignment-mode 2 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.1 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 2 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 1 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --threads 96 --compressed 0 -v 3

result2profile result_query_20230412_142303/qdb /home/username/project/my_local_DB/target_DB.idx result_query_20230412_142303/tmp/18292001434761310910/aln_0 result_query_20230412_142303/tmp/18292001434761310910/profile_0 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -e 0.1 --mask-profile 1 --e-profile 0.1 --comp-bias-corr 1 --comp-bias-corr-scale 1 --wg 0 --allow-deletion 0 --filter-msa 1 --filter-min-enable 0 --max-seq-id 0.9 --qid '0.0' --qsc -20 --cov 0 --diff 1000 --pseudo-cnt-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --db-load-mode 2 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --gap-pc 10 --threads 96 --compressed 0 -v 3

subtractdbs result_query_20230412_142303/tmp/18292001434761310910/pref_tmp_1 result_query_20230412_142303/tmp/18292001434761310910/aln_0 result_query_20230412_142303/tmp/18292001434761310910/pref_1 --threads 96 --e-profile 0.1 -e 0.1 --compressed 0 -v 3

subtractdbs result_query_20230412_142303/tmp/18292001434761310910/pref_tmp_1 result_query_20230412_142303/tmp/18292001434761310910/aln_0 result_query_20230412_142303/tmp/18292001434761310910/pref_1 --threads 96 --e-profile 0.1 -e 0.1 --compressed 0 -v 3

align result_query_20230412_142303/tmp/18292001434761310910/profile_0 /home/username/project/my_local_DB/target_DB.idx result_query_20230412_142303/tmp/18292001434761310910/pref_1 result_query_20230412_142303/tmp/18292001434761310910/aln_tmp_1 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 1 --alignment-mode 2 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.1 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 2 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --threads 96 --compressed 0 -v 3

mergedbs result_query_20230412_142303/tmp/18292001434761310910/profile_0 result_query_20230412_142303/tmp/18292001434761310910/aln_1 result_query_20230412_142303/tmp/18292001434761310910/aln_0 result_query_20230412_142303/tmp/18292001434761310910/aln_tmp_1

rmdb result_query_20230412_142303/tmp/18292001434761310910/aln_0

rmdb result_query_20230412_142303/tmp/18292001434761310910/aln_tmp_1

result2profile result_query_20230412_142303/tmp/18292001434761310910/profile_0 /home/username/project/my_local_DB/target_DB.idx result_query_20230412_142303/tmp/18292001434761310910/aln_1 result_query_20230412_142303/tmp/18292001434761310910/profile_1 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -e 0.1 --mask-profile 1 --e-profile 0.1 --comp-bias-corr 1 --comp-bias-corr-scale 1 --wg 0 --allow-deletion 0 --filter-msa 1 --filter-min-enable 0 --max-seq-id 0.9 --qid '0.0' --qsc -20 --cov 0 --diff 1000 --pseudo-cnt-mode 0 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --db-load-mode 2 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --gap-pc 10 --threads 96 --compressed 0 -v 3

prefilter result_query_20230412_142303/tmp/18292001434761310910/profile_1 /home/username/project/my_local_DB/target_DB.idx result_query_20230412_142303/tmp/18292001434761310910/pref_tmp_2 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' --seed-sub-mat 'aa:VTML80.out,nucl:nucleotide.out' -s 8 -k 0 --k-score seq:2147483647,prof:2147483647 --alph-size aa:21,nucl:5 --max-seq-len 65535 --max-seqs 10000 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --comp-bias-corr-scale 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-prob 0.9 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 2 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --threads 96 --compressed 0 -v 3

subtractdbs result_query_20230412_142303/tmp/18292001434761310910/pref_tmp_2 result_query_20230412_142303/tmp/18292001434761310910/aln_1 result_query_20230412_142303/tmp/18292001434761310910/pref_2 --threads 96 --e-profile 0.1 -e 0.1 --compressed 0 -v 3

subtractdbs result_query_20230412_142303/tmp/18292001434761310910/pref_tmp_2 result_query_20230412_142303/tmp/18292001434761310910/aln_1 result_query_20230412_142303/tmp/18292001434761310910/pref_2 --threads 96 --e-profile 0.1 -e 0.1 --compressed 0 -v 3

align result_query_20230412_142303/tmp/18292001434761310910/profile_1 /home/username/project/my_local_DB/target_DB.idx result_query_20230412_142303/tmp/18292001434761310910/pref_2 result_query_20230412_142303/tmp/18292001434761310910/aln_tmp_2 --sub-mat 'aa:blosum62.out,nucl:nucleotide.out' -a 1 --alignment-mode 2 --alignment-output-mode 0 --wrapped-scoring 0 -e 0.1 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --comp-bias-corr-scale 1 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 2 --pca substitution:1.100,context:1.400 --pcb substitution:4.100,context:5.800 --score-bias 0 --realign 0 --realign-score-bias -0.2 --realign-max-seqs 2147483647 --corr-score-weight 0 --gap-open aa:11,nucl:5 --gap-extend aa:1,nucl:2 --zdrop 40 --threads 96 --compressed 0 -v 3

mergedbs result_query_20230412_142303/tmp/18292001434761310910/profile_1 result_query_20230412_142303/res result_query_20230412_142303/tmp/18292001434761310910/aln_1 result_query_20230412_142303/tmp/18292001434761310910/aln_tmp_2

rmdb result_query_20230412_142303/tmp/18292001434761310910/aln_1

rmdb result_query_20230412_142303/tmp/18292001434761310910/aln_tmp_2

expandaln result_query_20230412_142303/qdb /home/username/project/my_local_DB/target_DB.idx result_query_20230412_142303/res /home/username/project/my_local_DB/target_DB.idx result_query_20230412_142303/res_exp --db-load-mode 2 --threads 96 --expansion-mode 0 -e 1.7976931348623157e+308 --expand-filter-clusters 1 --max-seq-id 0.95

  MMseqs Version:             67949d702dbfc6e5d54fdd0f14a9ab6740f11c32
  Expansion mode              0
  Substitution matrix         aa:blosum62.out,nucl:nucleotide.out
  Gap open cost               aa:11,nucl:5
  Gap extension cost          aa:1,nucl:2
  Max sequence length         65535
  Score bias                  0
  Compositional bias          1
  Compositional bias          1
  E-value threshold           1.79769e+308
  Seq. id. threshold          0
  Coverage threshold          0
  Coverage mode               0
  Pseudo count mode           0
  Pseudo count a              substitution:1.100,context:1.400
  Pseudo count b              substitution:4.100,context:5.800
  Expand filter clusters      1
  Use filter only at N seqs   0
  Maximum seq. id. threshold  0.95
  Minimum seq. id.            0.0
  Minimum score per column    -20
  Minimum coverage            0
  Select N most diverse seqs  1000
  Preload mode                2
  Compressed                  0
  Threads                     96
  Verbosity                   3


Index version: 16
Generated by:  67949d702dbfc6e5d54fdd0f14a9ab6740f11c32
ScoreMatrix:  VTML80.out
Index version: 16
Generated by:  67949d702dbfc6e5d54fdd0f14a9ab6740f11c32
ScoreMatrix:  VTML80.out
Invalid database read for database data file=/home/username/project/my_local_DB/target_DB.idx, database index=/home/username/project/my_local_DB/target_DB.idx.index
getData: local id (4294967295) >= db size (22)
Traceback (most recent call last):
  File "/home/username/project/colabfold_batch/colabfold-conda/bin/colabfold_search", line 8, in <module>
    sys.exit(main())
  File "/home/username/project/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/mmseqs/search.py", line 444, in main
    threads=args.threads,
  File "/home/username/project/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/mmseqs/search.py", line 86, in mmseqs_search_monomer
    run_mmseqs(mmseqs, ["expandaln", base.joinpath("qdb"), dbbase.joinpath(f"{uniref_db}{dbSuffix1}"), base.joinpath("res"), dbbase.joinpath(f"{uniref_db}{dbSuffix2}"), base.joinpath("res_exp"), "--db-load-mode", str(db_load_mode), "--threads", str(threads)] + expand_param)

  File "/home/username/project/colabfold_batch/colabfold-conda/lib/python3.7/site-packages/colabfold/mmseqs/search.py", line 23, in run_mmseqs
    subprocess.check_call([mmseqs] + params)
  File "/home/username/project/colabfold_batch/colabfold-conda/lib/python3.7/subprocess.py", line 363, in check_call
    raise CalledProcessError(retcode, cmd)

subprocess.CalledProcessError: Command '[PosixPath('mmseqs'), 'expandaln', PosixPath('result_query_20230412_142303/qdb'), PosixPath('/home/username/project/my_local_DB/target_DB.idx'), PosixPath('result_query_20230412_142303/res'), PosixPath('/home/username/project/my_local_DB/target_DB.idx'), PosixPath('result_query_20230412_142303/res_exp'), '--db-load-mode', '2', '--threads', '96', '--expansion-mode', '0', '-e', '1.7976931348623157e+308', '--expand-filter-clusters', '1', '--max-seq-id', '0.95']' returned non-zero exit status 1.

```

`target_DB` is a brand new database; I have not added nor deleted records after its creation.

Please let me know if I can help with debugging.

Thank you. And thanks for `mmseqs`.

**Comment by Geraldene** [comment] 2023-09-05 07:57
@martin-steinegger I am encountering a similar error when using a custom database to generate the MSA to be used by Colabfold for structure prediction. 

`Invalid database read for database data file=/media/data/Databases/database_50_db.idx, database index=/media/data/Databases/database_50_db.idx.index
getData: local id (4294967295) >= db size (50)
Traceback (most recent call last):
  File "/media/data/tools/ColabFold/colabfold/mmseqs/search.py", line 487, in <module>
    main()
  File "/media/data/tools/ColabFold/colabfold/mmseqs/search.py", line 427, in main
    mmseqs_search_monomer(
  File "/media/data/tools/ColabFold/colabfold/mmseqs/search.py", line 108, in mmseqs_search_monomer
    run_mmseqs(mmseqs, ["expandaln", base.joinpath("prof_res"), dbbase.joinpath(f"{metagenomic_db}{dbSuffix1}"), base.joinpath("res_env"), dbbase.joinpath(f"{metagenomic_db}{dbSuffix2}"), base.joinpath("res_env_exp"), "-e", str(expand_eval), "--expansion-mode", "0", "--db-load-mode", str(db_load_mode), "--threads", str(threads)])
  File "/media/data/tools/ColabFold/colabfold/mmseqs/search.py", line 23, in run_mmseqs
    subprocess.check_call([mmseqs] + params)
  File "/media/data/tools/ColabFold/localcolabfold/colabfold-conda/lib/python3.10/subprocess.py", line 369, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '[PosixPath('mmseqs'), 'expandaln', PosixPath('test_msa/prof_res'), PosixPath('/media/data/Databases/BCR_database_50_db.idx'), PosixPath('test_msa/res_env'), PosixPath('/media/data/Databases/BCR_database_50_db.idx'), PosixPath('test_msa/res_env_exp'), '-e', 'inf', '--expansion-mode', '0', '--db-load-mode', '0', '--threads', '96']' returned non-zero exit status 1.`

**Comment by chasemc** [comment] 2024-01-19 21:56
Got this error today on r4.4xlarge and [fusion](https://seqera.io/fusion/)  via Nextflow on AWS Batch. Maybe it's a filesystem thing

[command.log](https://github.com/soedinglab/MMseqs2/files/13994933/command.log)
[command.sh.txt](https://github.com/soedinglab/MMseqs2/files/13994938/command.sh.txt)

**Comment by navvye** [comment] 2025-02-02 23:54
I'm getting the same error while running uniref30_2302_db.index and colabfold_envdb_202108
