### ISSUE TITLE
Input tmp/11852343083329585076/search_tmp/14954657116245379907/search/pref does not exist.

### ISSUE THREAD

**Issue by jw44lavo** [soedinglab/MMseqs2#325] opened 2020-07-01 12:24 UTC
## Expected Behavior
get standard annotation output --> works on some files and does not work on other files

## Current Behavior
Error:
Input tmp/11852343083329585076/search_tmp/14954657116245379907/search/pref does not exist.

## Steps to Reproduce + MMseqs Output 
[code.txt](https://github.com/soedinglab/MMseqs2/files/4857796/code.txt)

## Context
mmseqs easy-search fastq files

## Your Environment
MMseqs Version:                     	11.e1a1c
conda install -c conda-forge -c bioconda mmseqs2
Ubuntu 20.04 LTS, 64-bit

**Comment by milot-mirdita** [comment] 2020-07-01 12:57
The issue is basically that MMseqs2 cannot extract any putative protein ORFs from the nucleotide reads since the default minimum length threshold is too long. You can reduce this threshold with something like `--min-length 15` (15*3=45 nucl min length).

The error message is pretty bad, we should fix this. Btw `plass` include a `mergereads` module to produce merged reads from paired reads and produces a sequence database that can then be read by `mmseqs search` that might be useful to extend some of the read lengths a bit and produce better annotations.
You can also first run the complete `plass` workflow to produce assembled proteins that can be better annotated. Plass will also struggle with the same parameter though and would also need a shorter `--min-length`.

**Comment by jw44lavo** [comment] 2020-07-02 07:29
Thank you very much! This comments are a big help to understand the problem.

I know about plass and I'm using it too. I wanted to check the output differences between plass+mmeseqs and mmseqs only. But the mergereads function is a good tip to combine the paired-end inputs.

**Closed** 2020-07-03 06:12 UTC

**Comment by sanyalab** [comment] 2020-11-19 06:30
Hello,

I am using easy-cluster in the latest version of mmseqs2. I have given a random sample of 1000 protein sequences from 1.36 million protein sequences to cluster. Here is the command
`mmseqs easy-cluster sample.fasta SampleTest tmp --max-seqs 100 --mask 0 --min-seq-id 0.75 -c 0.8 --cov-mode 0 --similarity-type 1 --cluster-steps 7 --cluster-reassign 1`

I am getting the error
`Input /tmp/5803776248916823257/clu_tmp/6236462208301927627/seq_wrong_assigned_pref does not exist.`
`Error: swapdb2 reassign died`
`Error: Search died`

My input file is ok. Its in unix format, containing protein sequences that are full-length. I also cannot find the `--min-length` you talk about in this post. Please advice.

Thank you
Abhijit
