### ISSUE TITLE
mmseq2 taxonomy error if using old database

### ISSUE THREAD

**Issue by nick-youngblut** [soedinglab/MMseqs2#221] opened 2019-07-27 09:45 UTC
If I run `mmseqs taxonomy` with version 9.d36de on a taxonomy database created with version 8.fac81, then I get the following error:

```
[...]
Filter by numerical comparison to first row.
[=================================================================] 121.87K 21m 16s 334ms
Time for merging files: 1h 14m 39s 541ms
Time for processing: 2h 14m 15s 378ms
terminate called after throwing an instance of 'std::out_of_range'
terminate called recursively
terminate called recursively
  what():  map::atAborted
Error: Lca died
```

The database was created from uniclust90_2018_08.tar.gz. If I instead run  `mmseqs taxonomy` with version 8.fac81, then the job finishes successfully.

It appears that `mmseqs taxonomy` is not backwards-compatible, but it has no checks on the database to warn the user of this. Instead, the user gets a cryptic error message.

**Comment by martin-steinegger** [comment] 2019-07-27 23:39
We did not change the format of the taxonomical database. It should be compatible. Also the error you show here happens while closing the database I think. Could you please provide the whole log? Does the error also occur with the newest version of mmseqs?

**Comment by nick-youngblut** [comment] 2019-07-29 10:25
The error occurs with version 9.d36de, but not 8.fac81. Here's the entire log:

```
$ mmseqs taxonomy -e 1e-5 --max-seqs 200 --lca-ranks "kingdom:phylum:class:order:family:genus:species"  --threads 24    clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/mmseqs2_8.fac81/uniclust90_2018_08_db    clusters_rep-seqs.part-14_tax_db tmp_part-14
taxonomy -e 1e-5 --max-seqs 200 --lca-ranks kingdom:phylum:class:order:family:genus:species --threads 24 clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/mmseqs2_8.fac81/uniclust90_2018_08_db clusters_rep-seqs.part-14_tax_db tmp_part-14

MMseqs Version:                       	9.d36de
Substitution matrix                   	blosum62.out
Add backtrace                         	false
Alignment mode                        	2
E-value threshold                     	1e-05
Seq. id. threshold                    	0
Min. alignment length                 	0
Seq. id. mode                         	0
Alternative alignments                	0
Coverage threshold                    	0
Coverage mode                         	0
Max sequence length                   	65535
Compositional bias                    	1
Realign hits                          	false
Max reject                            	2147483647
Max accept                            	2147483647
Include identical seq. id.            	false
Preload mode                          	0
Pseudo count a                        	1
Pseudo count b                        	1.5
Score bias                            	0
Gap open cost                         	11
Gap extension cost                    	1
Threads                               	24
Compressed                            	0
Verbosity                             	3
Seed substitution matrix              	VTML80.out
Sensitivity                           	5.7
K-mer size                            	0
K-score                               	2147483647
Alphabet size                         	21
Max results per query                 	200
Previous max results per query
Split database                        	0
Split mode                            	2
Split memory limit                    	0
Diagonal scoring                      	1
Exact k-mer matching                  	0
Mask residues                         	1
Mask lower case residues              	0
Minimum diagonal score                	15
Spaced k-mers                         	1
Spaced k-mer pattern
Local temporary path
Rescore mode                          	0
Remove hits by seq. id. and coverage  	false
Sort results                          	0
Global diagonal rescoring             	false
Mask profile                          	1
Profile e-value threshold             	0.001
Use global sequence weighting         	false
Filter MSA                            	1
Maximum seq. id. threshold            	0.9
Minimum seq. id.                      	0
Minimum score per column              	-20
Minimum coverage                      	0
Select N most diverse seqs            	1000
Omit consensus                        	false
Min codons in orf                     	30
Max codons in length                  	32734
Max orf gaps                          	2147483647
Contig start mode                     	2
Contig end mode                       	2
Orf start mode                        	1
Forward frames                        	1,2,3
Reverse frames                        	1,2,3
Translation table                     	1
Use all table starts                  	false
Offset of numeric ids                 	0
Add orf stop                          	false
Chain overlapping alignments          	0
Merge query                           	1
Search type                           	0
Number search iterations              	1
Start sensitivity                     	4
Search steps                          	1
Run a seq-profile search in slice mode	false
Strand selection                      	1
Disk space limit                      	0
MPI runner
Force restart with latest tmp         	false
Remove temporary files                	false
LCA ranks                             	kingdom:phylum:class:order:family:genus:species
Blacklisted taxa                      	12908,28384
Show taxon lineage                    	false
LCA mode                              	3
Taxonomy output mode                  	0
Match sequences by their id.          	false
Remove temporary files                	false
MPI runner

search clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/mmseqs2_8.fac81/uniclust90_2018_08_db tmp_part-14/17957680840564044329/first tmp_part-14/17957680840564044329/tmp_hsp1 --sub-mat blosum62.out -a 0 --alignment-mode 2 -e 1e-05 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 24 --compressed 0 -v 3 --seed-sub-mat VTML80.out -s 5.7 -k 0 --k-score 2147483647 --alph-size 21 --max-seqs 200 --split 0 --split-mode 2 --split-memory-limit 0 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 15 --spaced-kmer-mode 1 --rescore-mode 0 --filter-hits 0 --sort-results 0 --global-alignment 0 --mask-profile 1 --e-profile 0.001 --wg 0 --filter-msa 1 --max-seq-id 0.9 --qid 0 --qsc -20 --cov 0 --diff 1000 --omit-consensus 0 --min-length 30 --max-length 32734 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --use-all-table-starts 0 --id-offset 0 --add-orf-stop 0 --chain-alignments 0 --merge-query 1 --search-type 0 --num-iterations 1 --start-sens 4 --sens-steps 1 --slice-search 0 --strand 1 --disk-space-limit 0 --force-reuse 0 --remove-tmp-files 0

prefilter clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/mmseqs2_8.fac81/uniclust90_2018_08_db tmp_part-14/17957680840564044329/tmp_hsp1/2842639954524457022/pref_0 --sub-mat blosum62.out --seed-sub-mat VTML80.out -k 0 --k-score 2147483647 --alph-size 21 --max-seq-len 65535 --max-seqs 200 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca 1 --pcb 1.5 --threads 24 --compressed 0 -v 3 -s 5.7

Using 24 threads.
Estimated memory consumption 413414 MB
Target database size: 119988216 type: Aminoacid
Query database size: 40624 type: Aminoacid
Process prefiltering step 1 of 1

Index table k-mer threshold: 122 at k-mer size 7
Index table: counting k-mers
[=================================================================] 100.00% 119.99M 14m 40s 186ms
Index table: Masked residues: 372860390
Index table: fill
[=================================================================] 100.00% 119.99M 20m 55s 996ms
Index statistics
Entries:          38076912867
DB size:          227643 MB
Avg k-mer size:   29.747588
Top 10 k-mers
    SGQQRIA	281769
    GPGGKLL	259328
    GQQVARA	172987
    YTGTGKG	166889
    GGQRVAR	143134
    LLGPGKT	113836
    LSGQQAI	94348
    GGRRVAR	94149
    ALGSGKS	92540
    GRFVVEV	90006
Time for index table init: 0h 36m 49s 783ms
k-mer similarity threshold: 122
Starting prefiltering scores calculation (step 1 of 1)
Query db start  1 to 40624
Target db start  1 to 119988216
[=================================================================] 100.00% 40.62K 15m 11s 627ms

2741.257489 k-mers per position
7347947 DB matches per sequence
0 overflows
199 sequences passed prefiltering per query sequence
200 median result list length
0 sequences with 0 size result lists

Time for prefiltering scores calculation: 0h 15m 16s 157ms
Time for merging files: 0h 0m 0s 63ms
Time for processing: 0h 53m 6s 0ms
align clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/mmseqs2_8.fac81/uniclust90_2018_08_db tmp_part-14/17957680840564044329/tmp_hsp1/2842639954524457022/pref_0 tmp_part-14/17957680840564044329/first --sub-mat blosum62.out -a 0 --alignment-mode 2 -e 1e-05 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 24 --compressed 0 -v 3

Compute score and coverage
Query database size: 40624 type: Aminoacid
Target database size: 119988216 type: Aminoacid
Calculation of alignments
[=================================================================] 100.00% 40.62K 1m 1s 328ms
Time for merging files: 0h 0m 0s 46ms

8122882 alignments calculated.
4578438 sequence pairs passed the thresholds (0.563647 of overall calculated).
112.702789 hits per query sequence.
Time for processing: 0h 1m 18s 442ms
filterdb tmp_part-14/17957680840564044329/first tmp_part-14/17957680840564044329/top1 --extract-lines 1

Filtering by extracting the first 1 lines.
[=================================================================] 100.00% 40.62K 0s 978ms
Time for merging files: 0h 0m 0s 210ms
Time for processing: 0h 0m 1s 489ms
extractalignedregion clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/mmseqs2_8.fac81/uniclust90_2018_08_db tmp_part-14/17957680840564044329/top1 tmp_part-14/17957680840564044329/aligned --extract-mode 2

[=================================================================] 100.00% 40.62K 0s 140ms
Time for merging files: 0h 0m 0s 205ms
Time for processing: 0h 0m 16s 657ms
createsubdb tmp_part-14/17957680840564044329/aligned tmp_part-14/17957680840564044329/first tmp_part-14/17957680840564044329/first_sub

Time for merging files: 0h 0m 0s 8ms
Time for processing: 0h 0m 0s 477ms
align tmp_part-14/17957680840564044329/aligned /ebio/abt3_projects/databases_no-backup/uniclust/mmseqs2_8.fac81/uniclust90_2018_08_db tmp_part-14/17957680840564044329/first_sub tmp_part-14/17957680840564044329/round2 --sub-mat blosum62.out -a 0 --alignment-mode 2 -e 1e-05 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 24 --compressed 0 -v 3

Compute score and coverage
Query database size: 31979 type: Aminoacid
Target database size: 119988216 type: Aminoacid
Calculation of alignments
[=================================================================] 100.00% 31.98K 20s 768ms
Time for merging files: 0h 0m 0s 85ms

4578438 alignments calculated.
4551951 sequence pairs passed the thresholds (0.994215 of overall calculated).
142.341873 hits per query sequence.
Time for processing: 0h 0m 36s 82ms
mergedbs tmp_part-14/17957680840564044329/top1 tmp_part-14/17957680840564044329/merged tmp_part-14/17957680840564044329/top1 tmp_part-14/17957680840564044329/round2

Merging the results to tmp_part-14/17957680840564044329/merged
Time for merging files: 0h 0m 0s 11ms
Time for processing: 0h 0m 0s 699ms
filterdb tmp_part-14/17957680840564044329/merged tmp_part-14/17957680840564044329/2b_ali --beats-first --filter-column 4 --comparison-operator le

Filter by numerical comparison to first row.
[=================================================================] 100.00% 40.62K 0s 991ms
Time for merging files: 0h 0m 0s 235ms
Time for processing: 0h 0m 1s 633ms
lca /ebio/abt3_projects/databases_no-backup/uniclust/mmseqs2_8.fac81/uniclust90_2018_08_db tmp_part-14/17957680840564044329/2b_ali clusters_rep-seqs.part-14_tax_db --compressed 0 --lca-ranks kingdom:phylum:class:order:family:genus:species --blacklist 12908,28384 --tax-lineage 0 --threads 24 -v 3

Loading NCBI taxonomy
Loading nodes file ... Done, got 2043406 nodes
Loading merged file ... Done, added 52532 merged nodes.
Loading names file ... Done
Making matrix ... Done
Init RMQ ...Done
Computing LCA
terminate called after throwing an instance of 'std::out_of_range'] 0.11% 0.46  eta 1h 20m 23s
terminate called recursively
Aborted
Error: Lca died
```

**Comment by milot-mirdita** [comment] 2019-07-29 12:24
You might be running into issue #212. The problem is fixed in git master and will be included in the next release. Could you try if the latest git also crashes with the database from release 8?

**Comment by nick-youngblut** [comment] 2019-07-29 15:10
I'm not sure if this is the same problem or a different one, but I'm getting a similar error when using a different taxonomy database:

```
Loading NCBI taxonomy...
Computing LCA...
Segmentation fault
Error: Lca died
```

The database creation was (using version 8.fac81):

```
## downloading uniclust db
wget http://gwdu111.gwdg.de/~compbiol/uniclust/2018_08/uniclust50_2018_08.tar.gz
uncomp uniclust50_2018_08.tar.gz
mv uniclust50_2018_08/uniclust50_2018_08_consensus.fasta .

## creating seq db
mmseqs createdb --dbtype 1 uniclust50_2018_08_consensus.fasta uniclust50_2018_08_consensus

## creating tax db
mmseqs createtaxdb uniclust50_2018_08_consensus tmp
```

The taxonomy classify command (using version 8.fac81):

```
mmseqs taxonomy -e 1e-5 --max-seqs 200 --lca-ranks "kingdom:phylum:class:order:family:genus:species"  --threads 24    clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus    clusters_rep-seqs.part-14_tax_db tmp_part-14
```

The run log w/ error:

```
Program call:
taxonomy -e 1e-5 --max-seqs 200 --lca-ranks kingdom:phylum:class:order:family:genus:species --threads 24 clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus clusters_rep-seqs.part-14_tax_db tmp_part-14

MMseqs Version:                                                           	8.fac81
Substitution Matrix                                                       	blosum62.out
Add backtrace                                                             	false
Alignment mode                                                            	2
E-value threshold                                                         	1e-05
Seq. Id Threshold                                                         	0
Min. alignment length                                                     	0
Seq. Id. Mode                                                             	0
Alternative alignments                                                    	0
Coverage threshold                                                        	0
Coverage Mode                                                             	0
Max. sequence length                                                      	65535
Compositional bias                                                        	1
Realign hit                                                               	false
Max Reject                                                                	2147483647
Max Accept                                                                	2147483647
Include identical Seq. Id.                                                	false
Preload mode                                                              	0
Pseudo count a                                                            	1
Pseudo count b                                                            	1.5
Score bias                                                                	0
Gap open cost                                                             	11
Gap extension cost                                                        	1
Threads                                                                   	24
Compressed                                                                	0
Verbosity                                                                 	3
Seed Substitution Matrix                                                  	VTML80.out
Sensitivity                                                               	5.7
K-mer size                                                                	0
K-score                                                                   	2147483647
Alphabet size                                                             	21
Max. results per query                                                    	200
Offset result                                                             	0
Split DB                                                                  	0
Split mode                                                                	2
Split Memory Limit                                                        	0
Diagonal Scoring                                                          	1
Exact k-mer matching                                                      	0
Mask Residues                                                             	1
Mask lower case residues                                                  	0
Minimum Diagonal score                                                    	15
Spaced Kmer                                                               	1
Spaced k-mer pattern
Local temporary path
Rescore mode                                                              	0
Remove hits by seq.id. and coverage                                       	false
Sort results                                                              	0
In substitution scoring mode, performs global alignment along the diagonal	false
Mask profile                                                              	1
Profile e-value threshold                                                 	0.001
Use global sequence weighting                                             	false
Filter MSA                                                                	1
Maximum sequence identity threshold                                       	0.9
Minimum seq. id.                                                          	0
Minimum score per column                                                  	-20
Minimum coverage                                                          	0
Select n most diverse seqs                                                	1000
Omit Consensus                                                            	false
Min codons in orf                                                         	30
Max codons in length                                                      	32734
Max orf gaps                                                              	2147483647
Contig start mode                                                         	2
Contig end mode                                                           	2
Orf start mode                                                            	1
Forward Frames                                                            	1,2,3
Reverse Frames                                                            	1,2,3
Translation Table                                                         	1
Use all table starts                                                      	false
Offset of numeric ids                                                     	0
Add Orf Stop                                                              	false
Chain overlapping alignments                                              	0
Search type                                                               	0
Number search iterations                                                  	1
Start sensitivity                                                         	4
Search steps                                                              	1
Run a seq-profile search in slice mode                                    	false
Strand selection                                                          	1
Disk space limit                                                          	0
Sets the MPI runner
Force restart using the latest tmp                                        	false
Remove Temporary Files                                                    	false
LCA Ranks                                                                 	kingdom:phylum:class:order:family:genus:species
Blacklisted Taxa                                                          	12908,28384
LCA Mode                                                                  	3
Match sequences by their ID                                               	false
Remove Temporary Files                                                    	false
Sets the MPI runner

Program call:
search clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus tmp_part-14/8093924424180559474/first tmp_part-14/8093924424180559474/tmp_hsp1 --sub-mat blosum62.out -a 0 --alignment-mode 2 -e 1e-05 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 24 --compressed 0 -v 3 --seed-sub-mat VTML80.out -s 5.7 -k 0 --k-score 2147483647 --alph-size 21 --max-seqs 200 --offset-result 0 --split 0 --split-mode 2 --split-memory-limit 0 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 15 --spaced-kmer-mode 1 --rescore-mode 0 --filter-hits 0 --sort-results 0 --global-alignment 0 --mask-profile 1 --e-profile 0.001 --wg 0 --filter-msa 1 --max-seq-id 0.9 --qid 0 --qsc -20 --cov 0 --diff 1000 --omit-consensus 0 --min-length 30 --max-length 32734 --max-gaps 2147483647 --contig-start-mode 2 --contig-end-mode 2 --orf-start-mode 1 --forward-frames 1,2,3 --reverse-frames 1,2,3 --translation-table 1 --use-all-table-starts 0 --id-offset 0 --add-orf-stop 0 --chain-alignments 0 --search-type 0 --num-iterations 1 --start-sens 4 --sens-steps 1 --slice-search 0 --strand 1 --disk-space-limit 0 --force-reuse 0 --remove-tmp-files 0

Program call:
prefilter clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus tmp_part-14/8093924424180559474/tmp_hsp1/12507882511714639255/pref_0 --sub-mat blosum62.out --seed-sub-mat VTML80.out -k 0 --k-score 2147483647 --alph-size 21 --max-seq-len 65535 --max-seqs 200 --offset-result 0 --split 0 --split-mode 2 --split-memory-limit 0 -c 0 --cov-mode 0 --comp-bias-corr 1 --diag-score 1 --exact-kmer-matching 0 --mask 1 --mask-lower-case 0 --min-ungapped-score 15 --add-self-matches 0 --spaced-kmer-mode 1 --db-load-mode 0 --pca 1 --pcb 1.5 --threads 24 --compressed 0 -v 3 -s 5.7

Initialising data structures...
Using 24 threads.
Substitution matrices...
Substitution matrices...
Could not find precomputed index. Compute index.
Touch data file /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus ... Done.
Use kmer size 7 and split 1 using Target split mode.
Needed memory (83288349429 byte) of total memory (973956888576 byte)
Target database: /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus(Size: 22555708)
Query database type: Aminoacid
Target database type: Aminoacid
Time for init: 0h 0m 14s 497ms
Query database: clusters_rep-seqs_db_14_30(size=40624)
Process prefiltering step 1 of 1

Index table k-mer threshold: 122
Index table: counting k-mers...
...................................................................................................	1 Mio. sequences processed
...................................................................................................	2 Mio. sequences processed
...................................................................................................	3 Mio. sequences processed
...................................................................................................	4 Mio. sequences processed
...................................................................................................	5 Mio. sequences processed
...................................................................................................	6 Mio. sequences processed
...................................................................................................	7 Mio. sequences processed
...................................................................................................	8 Mio. sequences processed
...................................................................................................	9 Mio. sequences processed
...................................................................................................	10 Mio. sequences processed
...................................................................................................	11 Mio. sequences processed
...................................................................................................	12 Mio. sequences processed
...................................................................................................	13 Mio. sequences processed
...................................................................................................	14 Mio. sequences processed
...................................................................................................	15 Mio. sequences processed
...................................................................................................	16 Mio. sequences processed
...................................................................................................	17 Mio. sequences processed
...................................................................................................	18 Mio. sequences processed
...................................................................................................	19 Mio. sequences processed
...................................................................................................	20 Mio. sequences processed
...................................................................................................	21 Mio. sequences processed
...................................................................................................	22 Mio. sequences processed
.......................................................
Index table: Masked residues: 8669313
Index table: fill...
...................................................................................................	1 Mio. sequences processed
...................................................................................................	2 Mio. sequences processed
...................................................................................................	3 Mio. sequences processed
...................................................................................................	4 Mio. sequences processed
...................................................................................................	5 Mio. sequences processed
...................................................................................................	6 Mio. sequences processed
...................................................................................................	7 Mio. sequences processed
...................................................................................................	8 Mio. sequences processed
...................................................................................................	9 Mio. sequences processed
...................................................................................................	10 Mio. sequences processed
...................................................................................................	11 Mio. sequences processed
...................................................................................................	12 Mio. sequences processed
...................................................................................................	13 Mio. sequences processed
...................................................................................................	14 Mio. sequences processed
...................................................................................................	15 Mio. sequences processed
...................................................................................................	16 Mio. sequences processed
...................................................................................................	17 Mio. sequences processed
...................................................................................................	18 Mio. sequences processed
...................................................................................................	19 Mio. sequences processed
...................................................................................................	20 Mio. sequences processed
...................................................................................................	21 Mio. sequences processed
...................................................................................................	22 Mio. sequences processed
.......................................................
Index table: removing duplicate entries...
Index table init done.

DB statistic
Entries:         6060547859
DB Size:         46603287154 (byte)
Avg Kmer Size:   4.7348
Top 10 Kmers
   	YTGTGKG		27032
	GRDQVRG		19640
	AYITSTG		18464
	GPGGKLL		16342
	LAMHETP		14157
	FLNSHRT		12009
	GRFVVEV		10802
	LLGPGKT		9824
	RAEGRAV		9174
	LAVYTST		8267
Min Kmer Size:   0
Empty list: 348429986

Time for index table init: 0h 5m 53s 443ms
k-mer similarity threshold: 122
k-mer match probability: 0

Starting prefiltering scores calculation (step 1 of 1)
Query db start  1 to 40624
Target db start  1 to 22555708
....
2740 k-mers per position.
1152092 DB matches per sequence.
0 Overflows.
199 sequences passed prefiltering per query sequence.
Median result list size: 200
1 sequences with 0 size result lists.

Time for prefiltering scores calculation: 0h 3m 25s 795ms
Time for merging files: 0h 0m 0s 53ms
Time for processing: 0h 9m 40s 316ms
Program call:
align clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus tmp_part-14/8093924424180559474/tmp_hsp1/12507882511714639255/pref_0 tmp_part-14/8093924424180559474/first --sub-mat blosum62.out -a 0 --alignment-mode 2 -e 1e-05 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 24 --compressed 0 -v 3

Init data structures...
Touch data file /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus ... Done.
Compute score and coverage.
Query database type: Aminoacid
Target database type: Aminoacid
Calculation of Smith-Waterman alignments.
....Time for merging files: 0h 0m 0s 44ms

All sequences processed.

8113542 alignments calculated.
2760008 sequence pairs passed the thresholds (0.340173 of overall calculated).
67.9403 hits per query sequence.
Time for processing: 0h 0m 25s 268ms
Program call:
filterdb tmp_part-14/8093924424180559474/first tmp_part-14/8093924424180559474/top1 --extract-lines 1

Filtering by extracting the first 1 lines.
....Time for merging files: 0h 0m 0s 198ms
Time for processing: 0h 0m 1s 251ms
Program call:
extractalignedregion clusters_rep-seqs_db_14_30 /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus tmp_part-14/8093924424180559474/top1 tmp_part-14/8093924424180559474/aligned --extract-mode 2

Query file: clusters_rep-seqs_db_14_30
Touch data file clusters_rep-seqs_db_14_30 ... Done.
Target file: /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus
Touch data file /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus ... Done.
Alignment database: tmp_part-14/8093924424180559474/top1
Start writing file to tmp_part-14/8093924424180559474/aligned
....Time for merging files: 0h 0m 0s 186ms
Time for processing: 0h 0m 3s 851ms
Program call:
createsubdb tmp_part-14/8093924424180559474/aligned tmp_part-14/8093924424180559474/first tmp_part-14/8093924424180559474/first_sub

Start writing to database tmp_part-14/8093924424180559474/first_sub
Time for merging files: 0h 0m 0s 7ms
Time for processing: 0h 0m 0s 279ms
Program call:
align tmp_part-14/8093924424180559474/aligned /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus tmp_part-14/8093924424180559474/first_sub tmp_part-14/8093924424180559474/round2 --sub-mat blosum62.out -a 0 --alignment-mode 2 -e 1e-05 --min-seq-id 0 --min-aln-len 0 --seq-id-mode 0 --alt-ali 0 -c 0 --cov-mode 0 --max-seq-len 65535 --comp-bias-corr 1 --realign 0 --max-rejected 2147483647 --max-accept 2147483647 --add-self-matches 0 --db-load-mode 0 --pca 1 --pcb 1.5 --score-bias 0 --gap-open 11 --gap-extend 1 --threads 24 --compressed 0 -v 3

Init data structures...
Touch data file /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus ... Done.
Compute score and coverage.
Query database type: Aminoacid
Target database type: Aminoacid
Calculation of Smith-Waterman alignments.
...Time for merging files: 0h 0m 0s 78ms

All sequences processed.

2760008 alignments calculated.
2676553 sequence pairs passed the thresholds (0.969763 of overall calculated).
84.362 hits per query sequence.
Time for processing: 0h 0m 15s 472ms
Program call:
mergedbs tmp_part-14/8093924424180559474/top1 tmp_part-14/8093924424180559474/merged tmp_part-14/8093924424180559474/top1 tmp_part-14/8093924424180559474/round2

Merging the results to tmp_part-14/8093924424180559474/merged
Done
Time for merging files: 0h 0m 0s 11ms
Time for processing: 0h 0m 0s 354ms
Program call:
filterdb tmp_part-14/8093924424180559474/merged tmp_part-14/8093924424180559474/2b_ali --beats-first --filter-column 4 --comparison-operator le

Filter by numerical comparison to first row.
....Time for merging files: 0h 0m 0s 229ms
Time for processing: 0h 0m 0s 732ms
Program call:
lca /ebio/abt3_projects/databases_no-backup/uniclust/uniclust50/mmseqs2_8.fac81/uniclust50_2018_08_consensus tmp_part-14/8093924424180559474/2b_ali clusters_rep-seqs.part-14_tax_db --compressed 0 --lca-ranks kingdom:phylum:class:order:family:genus:species --blacklist 12908,28384 --threads 24 -v 3

Loading NCBI taxonomy...
Computing LCA...
Segmentation fault
Error: Lca died
```

I'm going to try this again with Release 8.

**Comment by martin-steinegger** [comment] 2019-07-29 23:20
Could you please try the newest commit? Milot fixed some segmentation fault in the lca module  https://github.com/soedinglab/MMseqs2/issues/212 but the fix is only in the master branch.

**Comment by nick-youngblut** [comment] 2019-07-30 12:48
Trying the newest commit fixed the issue! Thanks!

However, I now have an issue with batching `mmseqs taxonomy` and then merging the resulting taxonomy database. I previously used `mmseqs mergedbs`, but now I get the following error: 

```
Input database "/tmp/global2/nyoungblut/LLMGAG_27929269397/taxonomy/clusters_rep-seqs.part-19_tax_db" is wrong!
Current input: Taxonomy. Allowed input: Unknown, Index, Nucleotide, Profile, Aminoacid, Alignment, Prefilter, Bi-directional prefilter, Clustering, Offsetted headers, Generic
```

I don't see any subcommand for merging taxonomy databases. How do I merge taxonomy databases with the most recent version of mmseqs?

**Comment by martin-steinegger** [comment] 2019-07-30 14:48
should be fixed in the newest version

**Closed** 2019-10-07 12:56 UTC
